name: Auto commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Write date and commit
        run: |
          echo "$(date +'%Y-%m-%d')" > CURRENT_DATE
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "Kongkawee"
          git add CURRENT_DATE
          git commit -m "Auto commit of $(date)" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
